config/routes.rb
Rails.application.routes.draw do

  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :podcasts do
    resources :likes 
    resources :comments
    
  end

  get 'search', to: "podcasts#search"

  get 'podcasts/new'

  post 'podcasts', to: 'podcasts#create'

  get 'podcast/:id', to: 'podcasts#show'

  get 'podcasts/:id/edit', to: 'podcasts#edit'

  patch 'podcasts/:id', to: 'podcasts#update'

  delete '/podcasts/:id', to: 'podcasts#destroy', as:'delete'

  root 'podcasts#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    #   
    #   if user.admin?
    #      can :manage, :all
    #   else
    #      can :read, :create, :update, :all
    #   end
    #
    #   user ||= User.new # guest user (not logged in)
    #   can :destroy, Post, user_id: user.id
    #   can :read, Post
    #   can :create, Post
    #   can :create, Comment #cualquiera puede crear un comentario
    #   can :destroy, Comment, user_id: user.id
    #   can :destroy, [Post, Comment], user_id: user.id
      if user.email != 'jesenio@master.cl'
        
        can :create, Podcast, user_id: user.id
        can :read, Podcast, user_id: user.id
        can :destroy, Podcast, user_id: user.id
    
        can :create, Comment, user_id: user.id
        can :read, Comment, user_id: user.id
        can :destroy, Comment, user_id: user.id
               


        else    
         can :manage, :all
      end
    end
  end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :podcast
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :podcast
  belongs_to :user

  
end

app/models/podcast.rb
class Podcast < ApplicationRecord
    has_one_attached :file

    validates :name, presence: true

    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy


    def countLike
        self.likes.count
        
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :podcasts
  has_many :comments
  has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :find_podcast
    
    before_action :find_comment, only: [:destroy]
    
    
    def create
        @comment = @podcast.comments.create(params[:comment].permit(:content))
        @comment.user_id = current_user.id
        @comment.save

        if @comment.save
            redirect_to podcast_path(@podcast)
        else
            render 'new'
        end
    end

    def destroy
        @comment.destroy
        redirect_to podcast_path(@podcast)
    end

private

    def find_podcast
        @podcast = Podcast.find(params[:podcast_id])
    end

    def find_comment
        @comment = @podcast.comments.find(params[:id])
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    before_action :authenticate_user!, only: [:show]

    before_action :find_podcast 

  def create
   
    if already_liked?
      
    flash[:notice] = "You can't like more than once"
    else
    @podcast.likes.create(user_id: current_user.id)
    end
    redirect_to podcast_path(@podcast)

    
  end 

  private

  def find_podcast
    @podcast = Podcast.find(params[:podcast_id])
  end
  

  def already_liked?
  Like.where(user_id: current_user.id, podcast_id:
  params[:podcast_id]).exists?
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :authenticate_user!, except: [:show,:index]

  def index
    if params[:q].present?
      @podcasts = Podcast.where('name like ?', "%#{params[:q]}%")
    else
   @podcasts = Podcast.all
    end
  
  end

  


  def new
    @podcast = Podcast.new
    
  end

  def create
    
    @podcast = Podcast.new(podcast_params)
    @podcast.user = current_user

   

    @podcast.save
    redirect_to podcasts_path
  end

  def show

    @podcast = Podcast.find(params[:id])
    @comments = Comment.where(podcast_id: @podcast).order("created_at DESC")
   
  end 

  def edit
    @podcast = Podcast.find(params[:id])
  end

  def update
    @podcast = Podcast.find(params[:id])
    @podcast.update(podcast_params)
    redirect_to podcasts_path

  end

  def destroy
    @podcast = Podcast.find(params[:id])
    @podcast.destroy
    redirect_to podcasts_path
  end

  

  private

  def podcast_params
    params.require(:podcast).permit(:name, :file)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/comments/_comment.html.erb
<% @comments.each do |comment| %>

<p><b> <%= comment.user.email%> </b></p>

<%= comment.content %>

    <% if can?(:destroy, comment)%>                                                                                                                                            
    <%= link_to "Delete comment",  [comment.podcast, comment], method: :delete %>
    <% end %>
<% end %>

<%= render 'comments/form'%>

app/views/comments/_form.html.erb
<%= form_for([@podcast, @podcast.comments.build]) do |f|%>

<br>

<h5> Leave a comment: </h5>

<%= f.text_area :content %>

<button type="button" class="btn btn-success"><%= f.submit %></button>



<% end%>

app/views/layouts/_jumbotron.html.erb
<%# <div class="jumbotron">
  <h1 class="display-1">Hello, world!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </p>
</div> %>
<br>
<div class="jumbotron jumbotron-fluid bg-dark text-white">
  <div class="container">
    <h1 class="display-1">Fijo te rei wn ;)</h1>
    <p class="lead text-center ">Solo los más graciosos seran reconocidos.</p>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
  <a class="navbar-brand" href="#">laferos</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= podcasts_path %>">All Podcast<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_user_registration_path %>">Sign Up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= user_session_path %>">Login</a>
      </li>
      <li class="nav-item">

        <a class="nav-link" href="<%= destroy_user_session_path %>" data-method='delete'>Log Out</a>
       
      </li>
      
    </ul>
    <form class="form-inline my-2 my-lg-0" action="<%= podcasts_path %>">
      <input class="form-control mr-sm-2" name="q" type="text" placeholder="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Laferos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content= "width=device-width, initial-scale=1.0">

    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/sketchy/bootstrap.min.css" rel="stylesheet" integrity="sha384-N8DsABZCqc1XWbg/bAlIDk7AS/yNzT5fcKzg/TwfmTuUqZhGquVmpb5VvfmLcMzp" crossorigin="anonymous">
   
    <link href="https://cdnjs.cloudflare.com/ajax/libs/octicons/8.5.0/build.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js' %>
  </head>

  <body>

    <%= render 'layouts/navbar' %>


    <%= render 'layouts/jumbotron'%>
    <div class="container">
    <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/podcasts/edit.html.erb
<div class="form-group">
<%= form_with model: Podcast, local: true  do |f|%>
   <%= f.label :name, "Name your Podcast" %>

    <%= f.text_field :name %>

    <%= f.submit 'Create Podcast'%>
<% end %>
</div>

app/views/podcasts/index.html.erb
<%# <h1>Podcasts#index</h1>
<p>Find me in app/views/podcasts/index.html.erb</p> %>

<div class="container">
  <div class="row justify-content-center">
    <h1>Listen some Podcast!</h1>
  </div>
</div>

<br>

<div class="btn btn-success btn-lg btn-block">
  <%= link_to 'Crea', new_podcast_path, :class => "btn" %> 
  
</div>

<br>

<div class= "container">
    <table class="table table-dark table-hover">

    <thead>
    <tr>
      
      <th scope="col">Podcast name:</th>
      <th scope="col">Likes:</th>
      <th scope="col">Created by:</th>
    </tr>
    </thead>

    <% @podcasts.each do |podcast| %>
    
    <tbody>
    <tr>

        
       <td><%= podcast.name %></td>
        <td><%= podcast.countLike %></td>
       <td><%= podcast.user.email %></td>

       


       <td><%= link_to "show", podcast, class: 'btn btn-outline-success' %></td>


        <% if can?(:destroy, podcast)%>
              <td><%= link_to "delete", podcast, method: :delete, class: 'btn btn-outline-danger' %></td>
        <% end %>
    </tr>

    <% end %>
    </tbody>
    </table>

</div>

app/views/podcasts/new.html.erb
<div class="form-group">

<%= form_with model: @podcast, local: true do |f|%>

<div class = "field">

   <%= f.label :name, "Name your Podcast" %>

    <%= f.text_field :name %>

</div>

<div class = "field">

   <%= f.label :file, "Upload your podcast" %>

    <%= f.file_field :file %>
    
</div>

   

    <%= f.submit 'Create Podcast'%>
<% end %>

   
</div>

app/views/podcasts/show.html.erb
 
 
 
  
  




<div class ="container">

        
        <audio controls ="media center">
        <source src='<%= url_for(@podcast.file) %>' type="audio/mpeg"> 
        </audio>
        
    

        <h5 class="card-title"><%= @podcast.name%><%= button_to 'Like', podcast_likes_path(@podcast), method: :post %><h5>
        
        <%= time_ago_in_words @podcast.created_at %>
        
        <p><%= @podcast.likes.count %> <%= (@podcast.likes.count) == 1 ? 'Like' : 'Likes'%></p>

        <p> <%= render 'comments/comment'%> </p>

   

        
</div>





 